name=TOBA
version=0.3.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Tobi's Building Automation (TOBA)
paragraph=Tobi's Building Automation (TOBA) is a set of programs to run on controllers and worker devices that represent actors and sensors in buildings.
category=Communication
url=https://github.com/TobiasKnauss/ArduinoLib_TOBA
architectures=*
